#!/usr/bin/env sh

# remove existing packages
rm -rf packages

# execute "git clone" for each line
awk -F"=|@" '{gsub(/ /, "", $1); print "git clone --branch " $3 " --depth 1 " $2 " packages/" $1}' packages.txt | sh
